# Animal Data

In [855]:
import numpy as np
import pandas as pd

In [856]:
data = pd.read_csv('animal_data_dirty1.csv')

In [857]:
data

     Animal type;Country;Weight kg;Body Length cm;Gender;Animal code;Latitude;Longitude;Animal name;Observation date;Data compiled by
0                     ;;;;;;;;;03.01.2024;James Johnson
1                     ;;;;;;;;;03.02.2024;James Johnson
2     European bison;Poland;930;335;male;;52.828845;...
3     European bison;Poland;909;311;not determined;;...
4     European bison™;Poland;581;277;female;;52.8341...
...                                                 ...
1006  red squirrel;Poland;0.346;20;female;;52.212001...
1007  hedgehog;Germany;1;23;female;;49.561356;11.105...
1008  hedgehog;Germany;0.5;17;female;;49.561569;11.0...
1009  red squirrel;Poland;0.346;20;female;;52.212001...
1010  hedgehog;Hungary;0.9;16;female;;47.509860;18.9...

[1011 rows x 1 columns]

Looking at the dataset we can see it has little to no structure, if we looka  at the columns we can determine what structure the database it might try being in.

In [858]:
data.columns

Index(['Animal type;Country;Weight kg;Body Length cm;Gender;Animal code;Latitude;Longitude;Animal name;Observation date;Data compiled by'], dtype='object')

We only have 1 column but it is evident that it has not been distributed properly, and it is meant to be split by the semi colon (';'), if we check the first 5 entries, we can get a better look at the entries, and identify whether this pattern is consistent with the first few entries of the dataset

In [859]:
data.head()

  Animal type;Country;Weight kg;Body Length cm;Gender;Animal code;Latitude;Longitude;Animal name;Observation date;Data compiled by
0                  ;;;;;;;;;03.01.2024;James Johnson
1                  ;;;;;;;;;03.02.2024;James Johnson
2  European bison;Poland;930;335;male;;52.828845;...
3  European bison;Poland;909;311;not determined;;...
4  European bison™;Poland;581;277;female;;52.8341...

Both these issues can be fixed by changing how we read our csv file, making sure to split at each ';' character

In [860]:
data = pd.read_csv("animal_data_dirty1.csv", sep=';')

In [861]:
data

,Animal type,Country,Weight kg,Body Length cm,Gender,Animal code,Latitude,Longitude,Animal name,Observation date,Data compiled by
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.01.2024,James Johnson
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.02.2024,James Johnson
2,European bison,Poland,930.000,335.0,male,NaN,52.828845,23.820144,Szefu,01.03.2024,Anne Anthony
3,European bison,Poland,909.000,311.0,not determined,NaN,52.830509,23.826849,NaN,01.03.2024,Anne Anthony
4,European bison™,Poland,581.000,277.0,female,NaN,52.834109,23.807093,NaN,01.03.2024,Anne Anthony
...,...,...,...,...,...,...,...,...,...,...,...
1006,red squirrel,Poland,0.346,20.0,female,NaN,52.212001,21.033187,Lola,7 May 2024,Anne Anthony
1007,hedgehog,Germany,1.000,23.0,female,NaN,49.561356,11.105334,NaN,7 May 2024,Bob Bobson
1008,hedgehog,Germany,0.500,17.0,female,NaN,49.561569,11.087046,NaN,7 May 2024,Bob Bobson
1009,red squirrel,Poland,0.346,20.0,female,NaN,52.212001,21.033187,Lola,7 May 2024,Anne Anthony
1010,hedgehog,Hungary,0.900,16.0,female,NaN,47.509860,18.939943,NaN,8 May 2024,Anne Anthony

In [862]:
data['Gender'].unique()

array([nan, 'male', 'not determined', 'female'], dtype=object)

In [863]:
data.head()

,Animal type,Country,Weight kg,Body Length cm,Gender,Animal code,Latitude,Longitude,Animal name,Observation date,Data compiled by
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.01.2024,James Johnson
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.02.2024,James Johnson
2,European bison,Poland,930.0,335.0,male,NaN,52.828845,23.820144,Szefu,01.03.2024,Anne Anthony
3,European bison,Poland,909.0,311.0,not determined,NaN,52.830509,23.826849,NaN,01.03.2024,Anne Anthony
4,European bison™,Poland,581.0,277.0,female,NaN,52.834109,23.807093,NaN,01.03.2024,Anne Anthony

In [864]:
data['Animal type'].unique()

array([nan, 'European bison', 'European bison™', 'European bisson',
       'European buster', 'lynx', 'lynx?', 'red squirel', 'red squirrel',
       'red squirrell', 'hedgehog', 'wedgehod', 'ledgehod'], dtype=object)

In [865]:
data.size

11121

In [866]:
data.loc[data['Animal type'].str.contains('European', case=True, na=False), 'Animal type'] = 'European Bison'

data.loc[data['Animal type'].str.contains('lynx', case=False, na=False), 'Animal type'] = 'Lynx'

data.loc[data['Animal type'].str.contains('red squirrel', case=False, na=False), 'Animal type'] = 'Red Squirrel'

data.loc[data['Animal type'].str.contains('red squirel', case=False, na=False), 'Animal type'] = 'Red Squirrel'

data.loc[data['Animal type'].str.contains('edgeho', case=False, na=False), 'Animal type'] = 'Hedgehog'

In [867]:
data['Animal type'].unique()

array([nan, 'European Bison', 'Lynx', 'Red Squirrel', 'Hedgehog'],
      dtype=object)

In [868]:
data

,Animal type,Country,Weight kg,Body Length cm,Gender,Animal code,Latitude,Longitude,Animal name,Observation date,Data compiled by
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.01.2024,James Johnson
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.02.2024,James Johnson
2,European Bison,Poland,930.000,335.0,male,NaN,52.828845,23.820144,Szefu,01.03.2024,Anne Anthony
3,European Bison,Poland,909.000,311.0,not determined,NaN,52.830509,23.826849,NaN,01.03.2024,Anne Anthony
4,European Bison,Poland,581.000,277.0,female,NaN,52.834109,23.807093,NaN,01.03.2024,Anne Anthony
...,...,...,...,...,...,...,...,...,...,...,...
1006,Red Squirrel,Poland,0.346,20.0,female,NaN,52.212001,21.033187,Lola,7 May 2024,Anne Anthony
1007,Hedgehog,Germany,1.000,23.0,female,NaN,49.561356,11.105334,NaN,7 May 2024,Bob Bobson
1008,Hedgehog,Germany,0.500,17.0,female,NaN,49.561569,11.087046,NaN,7 May 2024,Bob Bobson
1009,Red Squirrel,Poland,0.346,20.0,female,NaN,52.212001,21.033187,Lola,7 May 2024,Anne Anthony
1010,Hedgehog,Hungary,0.900,16.0,female,NaN,47.509860,18.939943,NaN,8 May 2024,Anne Anthony

In [869]:
data.loc[data['Animal type'].isna()]

,Animal type,Country,Weight kg,Body Length cm,Gender,Animal code,Latitude,Longitude,Animal name,Observation date,Data compiled by
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.01.2024,James Johnson
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.02.2024,James Johnson
111,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.03.2024,James Johnson
164,NaN,Austria,0.263,22.0,male,NaN,NaN,NaN,NaN,05.03.2024,Bob Bobson
563,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.04.2024,James Johnson
626,NaN,Austria,0.319,20.0,male,NaN,NaN,NaN,NaN,06.04.2024,Bob Bobson
627,NaN,Austria,0.292,19.0,female,NaN,NaN,NaN,NaN,06.04.2024,Bob Bobson
628,NaN,Austria,0.319,19.0,female,NaN,NaN,NaN,NaN,06.04.2024,Bob Bobson
629,NaN,Austria,0.298,20.0,male,NaN,NaN,NaN,NaN,06.04.2024,Bob Bobson
630,NaN,Austria,0.255,22.0,male,NaN,NaN,NaN,NaN,06.04.2024,Bob Bobson
631,NaN,Austria,0.300,20.0,male,NaN,NaN,NaN,NaN,06.04.2024,Bob Bobson
632,NaN,Austria,0.252,21.0,male,NaN,NaN,NaN,NaN,06.04.2024,Bob Bobson
833,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.05.2024,James Johnson
934,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.06.2024,James Johnson
956,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.07.2024,James Johnson
963,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.08.2024,James Johnson
968,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.13.2024,James Johnson
969,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.14.2024,James Johnson
970,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.22.2024,James Johnson
971,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.22.2024,James Johnson

In [870]:
data['Weight kg'] = pd.to_numeric(data['Weight kg'], errors='coerce')

In [871]:
data.loc[data['Weight kg'] < 0.32, 'Animal type'].unique()

array(['Red Squirrel', nan], dtype=object)

Knowing that all animals less than 0.32 kg are Red Squirrel's, we can assign the NaN values to be Red Squirrels

In [872]:
data.loc[data['Animal type'].isna(), 'Animal type'] = 'Red Squirrel'

In [873]:
data['Animal type'].unique()

array(['Red Squirrel', 'European Bison', 'Lynx', 'Hedgehog'], dtype=object)

In [874]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1011 entries, 0 to 1010
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Animal type       1011 non-null   object
 1   Country           999 non-null    object
 2   Weight kg         984 non-null    float64
 3   Body Length cm    984 non-null    float64
 4   Gender            992 non-null    object
 5   Animal code       0 non-null      float64
 6   Latitude          913 non-null    float64
 7   Longitude         913 non-null    float64
 8   Animal name       52 non-null     object
 9   Observation date  1011 non-null   object
 10  Data compiled by  1011 non-null   object
dtypes: float64(5), object(6)
memory usage: 87.0+ KB

In [875]:
data['Country'].unique()

array([nan, 'Poland', 'Hungary', 'PL', 'Germany', 'Slovakia',
       'Czech Republic', 'Czech', 'Hungry', 'HU', 'Austria', 'Australia',
       'CZ', 'DE', 'CC'], dtype=object)

In [876]:
data.loc[data['Country'] == 'PL', 'Country'] = 'Poland'

data.loc[data['Country'].str.contains('Cz', case=False, na=False), 'Country'] = 'Czech Republic'

data.loc[data['Country'].str.contains('HU', case=False, na=False), 'Country'] = 'Hungary'

In [877]:
data['Country'].unique()

array([nan, 'Poland', 'Hungary', 'Germany', 'Slovakia', 'Czech Republic',
       'Austria', 'Australia', 'DE', 'CC'], dtype=object)

Unsure what Country CC so if we look at the lattitude and longitude of the observations we can determine the location

In [878]:
data.loc[data['Country'] == 'CC']

,Animal type,Country,Weight kg,Body Length cm,Gender,Animal code,Latitude,Longitude,Animal name,Observation date,Data compiled by
397,European Bison,CC,603.0,291.0,male,NaN,50.644813,14.839817,NaN,22.03.2024,John Johnson
398,European Bison,CC,717.0,305.0,male,NaN,50.635565,14.839320,NaN,22.03.2024,John Johnson
661,European Bison,CC,560.0,250.0,female,NaN,50.645077,14.840304,NaN,08.04.2024,John Johnson
777,European Bison,CC,656.0,245.0,female,NaN,50.643056,14.843037,NaN,19.04.2024,John Johnson

Looking into the coordinates of the Country CC records we find that they are also Czech Republic , we can fix this now

In [879]:
data.loc[data['Country'] == 'CC', 'Country'] = 'Czech Republic'

In [880]:
data['Country'].unique()

array([nan, 'Poland', 'Hungary', 'Germany', 'Slovakia', 'Czech Republic',
       'Austria', 'Australia', 'DE'], dtype=object)

In [881]:
data.loc[data['Country'].isin(['Australia', 'Austria'])]

,Animal type,Country,Weight kg,Body Length cm,Gender,Animal code,Latitude,Longitude,Animal name,Observation date,Data compiled by
164,Red Squirrel,Austria,0.263,22.0,male,NaN,NaN,NaN,NaN,05.03.2024,Bob Bobson
295,Hedgehog,Australia,0.800,24.0,not determined,NaN,47.781689,14.386777,NaN,14.03.2024,Bob Bobson
296,Hedgehog,Austria,0.700,19.0,female,NaN,47.781139,14.382004,NaN,14.03.2024,Bob Bobson
297,Hedgehog,Austria,0.800,20.0,male,NaN,47.781828,14.385001,NaN,14.03.2024,Bob Bobson
298,Hedgehog,Austria,0.600,14.0,female,NaN,47.781060,14.386807,NaN,14.03.2024,Bob Bobson
...,...,...,...,...,...,...,...,...,...,...,...
774,Hedgehog,Austria,0.900,25.0,male,NaN,47.317974,11.187472,NaN,19.04.2024,Bob Bobson
775,Hedgehog,Austria,1.100,22.0,male,NaN,47.316562,11.191160,NaN,19.04.2024,Bob Bobson
776,Hedgehog,Austria,1.200,24.0,male,NaN,47.318191,11.189484,NaN,19.04.2024,Bob Bobson
803,Lynx,Austria,20.000,90.0,male,NaN,47.781188,14.385356,NaN,24.04.2024,Bob Bobson
804,Lynx,Austria,26.000,91.0,female,NaN,47.780999,14.382120,NaN,24.04.2024,Bob Bobson

In [882]:
data.loc[data['Country'] == 'Australia']

,Animal type,Country,Weight kg,Body Length cm,Gender,Animal code,Latitude,Longitude,Animal name,Observation date,Data compiled by
295,Hedgehog,Australia,0.800,24.0,not determined,NaN,47.781689,14.386777,NaN,14.03.2024,Bob Bobson
370,Hedgehog,Australia,0.600,14.0,female,NaN,47.781248,14.382649,NaN,21.03.2024,Bob Bobson
583,Red Squirrel,Australia,0.266,20.0,female,NaN,47.781632,14.382365,NaN,05.04.2024,Bob Bobson
688,Red Squirrel,Australia,0.310,23.0,male,NaN,47.856092,15.083547,NaN,11.04.2024,Bob Bobson

Here we can see Bob Bobson has incorrectly assigned 4 entries to be in Australia instead of Austria, this is oobvious through the coordinates of the recordings

In [883]:
data.loc[data['Country'] == 'Australia', 'Country'] = 'Austria'

In [884]:
data['Country'].unique()

array([nan, 'Poland', 'Hungary', 'Germany', 'Slovakia', 'Czech Republic',
       'Austria', 'DE'], dtype=object)

In [885]:
data.loc[data['Country'] == 'DE']

,Animal type,Country,Weight kg,Body Length cm,Gender,Animal code,Latitude,Longitude,Animal name,Observation date,Data compiled by
371,Hedgehog,DE,1.100,21.0,male,NaN,52.585628,13.149093,Bob Bobson,21.03.2024,Bob Bobson
375,Red Squirrel,DE,0.276,21.0,female,NaN,52.581885,13.152811,Bob Bobson,21.03.2024,Bob Bobson
391,Red Squirrel,DE,0.306,23.0,male,NaN,52.584352,13.148089,Bob Bobson,22.03.2024,Bob Bobson
427,Hedgehog,DE,0.800,16.0,male,NaN,52.582072,13.149185,NaN,24.03.2024,Bob Bobson
465,Hedgehog,DE,0.700,17.0,male,NaN,48.161584,11.494938,NaN,27.03.2024,Bob Bobson

In [886]:
data.loc[data['Country'] == 'DE', 'Country'] = 'Denmark'

In [887]:
data['Country'].unique()

array([nan, 'Poland', 'Hungary', 'Germany', 'Slovakia', 'Czech Republic',
       'Austria', 'Denmark'], dtype=object)

In [888]:
data.loc[data['Country'].isna()]

,Animal type,Country,Weight kg,Body Length cm,Gender,Animal code,Latitude,Longitude,Animal name,Observation date,Data compiled by
0,Red Squirrel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.01.2024,James Johnson
1,Red Squirrel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.02.2024,James Johnson
111,Red Squirrel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.03.2024,James Johnson
563,Red Squirrel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.04.2024,James Johnson
833,Red Squirrel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.05.2024,James Johnson
934,Red Squirrel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.06.2024,James Johnson
956,Red Squirrel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.07.2024,James Johnson
963,Red Squirrel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.08.2024,James Johnson
968,Red Squirrel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.13.2024,James Johnson
969,Red Squirrel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.14.2024,James Johnson
970,Red Squirrel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.22.2024,James Johnson
971,Red Squirrel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.22.2024,James Johnson

In [889]:
data.loc[data['Data compiled by'] == 'James Johnson']

,Animal type,Country,Weight kg,Body Length cm,Gender,Animal code,Latitude,Longitude,Animal name,Observation date,Data compiled by
0,Red Squirrel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.01.2024,James Johnson
1,Red Squirrel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.02.2024,James Johnson
111,Red Squirrel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.03.2024,James Johnson
563,Red Squirrel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.04.2024,James Johnson
833,Red Squirrel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.05.2024,James Johnson
934,Red Squirrel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.06.2024,James Johnson
948,Lynx,Slovakia,15.000,65.0,female,NaN,48.406339,18.841071,NaN,03.07.2024,James Johnson
949,Lynx,Slovakia,18.000,85.0,male,NaN,48.411729,18.835591,NaN,03.07.2024,James Johnson
950,Red Squirrel,Slovakia,0.297,20.0,not determined,NaN,49.054132,22.411066,NaN,03.07.2024,James Johnson
951,Red Squirrel,Slovakia,0.273,23.0,female,NaN,49.055962,22.425527,NaN,03.07.2024,James Johnson
952,Red Squirrel,Slovakia,0.254,19.0,male,NaN,49.055646,22.412458,NaN,03.07.2024,James Johnson
953,Red Squirrel,Slovakia,0.305,20.0,female,NaN,49.052910,22.420861,NaN,03.07.2024,James Johnson
954,Red Squirrel,Slovakia,0.327,19.0,female,NaN,49.055547,22.411172,NaN,03.07.2024,James Johnson
955,Red Squirrel,Slovakia,0.305,20.0,male,NaN,49.054647,22.410445,NaN,03.07.2024,James Johnson
956,Red Squirrel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.07.2024,James Johnson
957,Hedgehog,Slovakia,1.000,17.0,male,NaN,48.226063,17.078596,NaN,05.07.2024,James Johnson
958,Hedgehog,Slovakia,0.600,16.0,female,NaN,48.238067,17.090891,NaN,05.07.2024,James Johnson
959,Hedgehog,Slovakia,1.100,20.0,female,NaN,48.239540,17.066719,NaN,05.07.2024,James Johnson
960,Red Squirrel,Slovakia,0.327,23.0,male,NaN,49.057284,22.423861,NaN,03.08.2024,James Johnson
961,Red Squirrel,Slovakia,0.319,22.0,female,NaN,49.054751,22.419160,NaN,03.08.2024,James Johnson
962,Red Squirrel,Slovakia,0.303,20.0,male,NaN,49.055930,22.424085,NaN,03.08.2024,James Johnson
963,Red Squirrel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.08.2024,James Johnson
964,Lynx,Slovakia,12.000,61.0,male,NaN,48.413928,18.835281,NaN,03.09.2024,James Johnson
965,Red Squirrel,Slovakia,0.309,20.0,female,NaN,49.057758,22.415169,NaN,03.09.2024,James Johnson
966,Red Squirrel,Slovakia,0.332,19.0,male,NaN,48.185695,17.090742,NaN,03.09.2024,James Johnson
967,Red Squirrel,Slovakia,0.331,18.0,female,NaN,48.186040,17.091147,NaN,03.11.2024,James Johnson
968,Red Squirrel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.13.2024,James Johnson
969,Red Squirrel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.14.2024,James Johnson
970,Red Squirrel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.22.2024,James Johnson
971,Red Squirrel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.22.2024,James Johnson

In [890]:
data = data[data['Country'].notna()]

In [891]:
data.loc[data['Data compiled by'] == 'James Johnson']

,Animal type,Country,Weight kg,Body Length cm,Gender,Animal code,Latitude,Longitude,Animal name,Observation date,Data compiled by
948,Lynx,Slovakia,15.000,65.0,female,NaN,48.406339,18.841071,NaN,03.07.2024,James Johnson
949,Lynx,Slovakia,18.000,85.0,male,NaN,48.411729,18.835591,NaN,03.07.2024,James Johnson
950,Red Squirrel,Slovakia,0.297,20.0,not determined,NaN,49.054132,22.411066,NaN,03.07.2024,James Johnson
951,Red Squirrel,Slovakia,0.273,23.0,female,NaN,49.055962,22.425527,NaN,03.07.2024,James Johnson
952,Red Squirrel,Slovakia,0.254,19.0,male,NaN,49.055646,22.412458,NaN,03.07.2024,James Johnson
953,Red Squirrel,Slovakia,0.305,20.0,female,NaN,49.052910,22.420861,NaN,03.07.2024,James Johnson
954,Red Squirrel,Slovakia,0.327,19.0,female,NaN,49.055547,22.411172,NaN,03.07.2024,James Johnson
955,Red Squirrel,Slovakia,0.305,20.0,male,NaN,49.054647,22.410445,NaN,03.07.2024,James Johnson
957,Hedgehog,Slovakia,1.000,17.0,male,NaN,48.226063,17.078596,NaN,05.07.2024,James Johnson
958,Hedgehog,Slovakia,0.600,16.0,female,NaN,48.238067,17.090891,NaN,05.07.2024,James Johnson
959,Hedgehog,Slovakia,1.100,20.0,female,NaN,48.239540,17.066719,NaN,05.07.2024,James Johnson
960,Red Squirrel,Slovakia,0.327,23.0,male,NaN,49.057284,22.423861,NaN,03.08.2024,James Johnson
961,Red Squirrel,Slovakia,0.319,22.0,female,NaN,49.054751,22.419160,NaN,03.08.2024,James Johnson
962,Red Squirrel,Slovakia,0.303,20.0,male,NaN,49.055930,22.424085,NaN,03.08.2024,James Johnson
964,Lynx,Slovakia,12.000,61.0,male,NaN,48.413928,18.835281,NaN,03.09.2024,James Johnson
965,Red Squirrel,Slovakia,0.309,20.0,female,NaN,49.057758,22.415169,NaN,03.09.2024,James Johnson
966,Red Squirrel,Slovakia,0.332,19.0,male,NaN,48.185695,17.090742,NaN,03.09.2024,James Johnson
967,Red Squirrel,Slovakia,0.331,18.0,female,NaN,48.186040,17.091147,NaN,03.11.2024,James Johnson

In [892]:
data['Country'].unique()

array(['Poland', 'Hungary', 'Germany', 'Slovakia', 'Czech Republic',
       'Austria', 'Denmark'], dtype=object)

In [893]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 999 entries, 2 to 1010
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Animal type       999 non-null    object
 1   Country           999 non-null    object
 2   Weight kg         984 non-null    float64
 3   Body Length cm    984 non-null    float64
 4   Gender            992 non-null    object
 5   Animal code       0 non-null      float64
 6   Latitude          913 non-null    float64
 7   Longitude         913 non-null    float64
 8   Animal name       52 non-null     object
 9   Observation date  999 non-null    object
 10  Data compiled by  999 non-null    object
dtypes: float64(5), object(6)
memory usage: 93.7+ KB

In [894]:
data['Animal type'].unique()

array(['European Bison', 'Lynx', 'Red Squirrel', 'Hedgehog'], dtype=object)

In [895]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 999 entries, 2 to 1010
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Animal type       999 non-null    object
 1   Country           999 non-null    object
 2   Weight kg         984 non-null    float64
 3   Body Length cm    984 non-null    float64
 4   Gender            992 non-null    object
 5   Animal code       0 non-null      float64
 6   Latitude          913 non-null    float64
 7   Longitude         913 non-null    float64
 8   Animal name       52 non-null     object
 9   Observation date  999 non-null    object
 10  Data compiled by  999 non-null    object
dtypes: float64(5), object(6)
memory usage: 93.7+ KB

In [896]:
data.loc[data['Weight kg'].isna()]

,Animal type,Country,Weight kg,Body Length cm,Gender,Animal code,Latitude,Longitude,Animal name,Observation date,Data compiled by
15,Red Squirrel,Poland,NaN,NaN,male,NaN,52.241177,21.052873,NaN,01.03.2024,Anne Anthony
57,Red Squirrel,Poland,NaN,NaN,male,NaN,52.241177,21.052873,NaN,01.03.2024,Anne Anthony
193,Hedgehog,Hungary,NaN,NaN,female,NaN,48.506206,20.565308,NaN,07.03.2024,Anne Anthony
273,Red Squirrel,Hungary,NaN,NaN,female,NaN,47.508454,18.949343,NaN,12.03.2024,Anne Anthony
278,Red Squirrel,Hungary,NaN,NaN,female,NaN,47.508454,18.949343,NaN,12.03.2024,Anne Anthony
367,Red Squirrel,Poland,NaN,NaN,male,NaN,50.041154,19.949919,NaN,21.03.2024,Anne Anthony
387,Red Squirrel,Poland,NaN,NaN,male,NaN,50.041154,19.949919,NaN,21.03.2024,Anne Anthony
521,Red Squirrel,Poland,NaN,NaN,male,NaN,50.041552,19.949984,NaN,02.04.2024,Anne Anthony
555,Red Squirrel,Poland,NaN,NaN,male,NaN,50.041552,19.949984,NaN,02.04.2024,Anne Anthony
707,Red Squirrel,Poland,NaN,NaN,male,NaN,50.041573,19.949850,NaN,13.04.2024,Anne Anthony
713,Red Squirrel,Poland,NaN,NaN,male,NaN,50.041573,19.949850,NaN,13.04.2024,Anne Anthony
861,Hedgehog,Hungary,NaN,NaN,male,NaN,47.510077,18.945646,NaN,17.05.2024,Anne Anthony
898,Red Squirrel,Poland,NaN,NaN,male,NaN,52.212906,21.033210,NaN,25.05.2024,Anne Anthony
899,Red Squirrel,Poland,NaN,NaN,male,NaN,52.212906,21.033210,NaN,25.05.2024,Anne Anthony
972,Hedgehog,Hungary,NaN,NaN,male,NaN,47.509755,18.949465,NaN,1 May 2024,Anne Anthony

In [897]:
male_RS_weight = data.loc[(data['Animal type'] == 'Red Squirrel') & (data['Gender'] == 'male'), 'Weight kg'].mean()

female_RS_weight = data.loc[(data['Animal type'] == 'Red Squirrel') & (data['Gender'] == 'female'), 'Weight kg'].mean()

male_H_weight = data.loc[(data['Animal type'] == 'Hedgehog') & (data['Gender'] == 'male'), 'Weight kg'].mean()

female_H_weight = data.loc[(data['Animal type'] == 'Hedgehog') & (data['Gender'] == 'female'), 'Weight kg'].mean()

In [898]:
data.loc[(data['Animal type'] == 'Red Squirrel') & (data['Gender'] == 'male'), 'Weight kg'] = male_RS_weight

data.loc[(data['Animal type'] == 'Red Squirrel') & (data['Gender'] == 'female'), 'Weight kg'] = female_RS_weight

data.loc[(data['Animal type'] == 'Hedgehog') & (data['Gender'] == 'male'), 'Weight kg'] = male_H_weight

data.loc[(data['Animal type'] == 'Hedgehog') & (data['Gender'] == 'female'), 'Weight kg'] = female_H_weight

In [899]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 999 entries, 2 to 1010
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Animal type       999 non-null    object
 1   Country           999 non-null    object
 2   Weight kg         999 non-null    float64
 3   Body Length cm    984 non-null    float64
 4   Gender            992 non-null    object
 5   Animal code       0 non-null      float64
 6   Latitude          913 non-null    float64
 7   Longitude         913 non-null    float64
 8   Animal name       52 non-null     object
 9   Observation date  999 non-null    object
 10  Data compiled by  999 non-null    object
dtypes: float64(5), object(6)
memory usage: 93.7+ KB

In [900]:
data.loc[data['Body Length cm'].isna()]

,Animal type,Country,Weight kg,Body Length cm,Gender,Animal code,Latitude,Longitude,Animal name,Observation date,Data compiled by
15,Red Squirrel,Poland,0.296900,NaN,male,NaN,52.241177,21.052873,NaN,01.03.2024,Anne Anthony
57,Red Squirrel,Poland,0.296900,NaN,male,NaN,52.241177,21.052873,NaN,01.03.2024,Anne Anthony
193,Hedgehog,Hungary,0.745926,NaN,female,NaN,48.506206,20.565308,NaN,07.03.2024,Anne Anthony
273,Red Squirrel,Hungary,0.291273,NaN,female,NaN,47.508454,18.949343,NaN,12.03.2024,Anne Anthony
278,Red Squirrel,Hungary,0.291273,NaN,female,NaN,47.508454,18.949343,NaN,12.03.2024,Anne Anthony
367,Red Squirrel,Poland,0.296900,NaN,male,NaN,50.041154,19.949919,NaN,21.03.2024,Anne Anthony
387,Red Squirrel,Poland,0.296900,NaN,male,NaN,50.041154,19.949919,NaN,21.03.2024,Anne Anthony
521,Red Squirrel,Poland,0.296900,NaN,male,NaN,50.041552,19.949984,NaN,02.04.2024,Anne Anthony
555,Red Squirrel,Poland,0.296900,NaN,male,NaN,50.041552,19.949984,NaN,02.04.2024,Anne Anthony
707,Red Squirrel,Poland,0.296900,NaN,male,NaN,50.041573,19.949850,NaN,13.04.2024,Anne Anthony
713,Red Squirrel,Poland,0.296900,NaN,male,NaN,50.041573,19.949850,NaN,13.04.2024,Anne Anthony
861,Hedgehog,Hungary,0.845652,NaN,male,NaN,47.510077,18.945646,NaN,17.05.2024,Anne Anthony
898,Red Squirrel,Poland,0.296900,NaN,male,NaN,52.212906,21.033210,NaN,25.05.2024,Anne Anthony
899,Red Squirrel,Poland,0.296900,NaN,male,NaN,52.212906,21.033210,NaN,25.05.2024,Anne Anthony
972,Hedgehog,Hungary,0.845652,NaN,male,NaN,47.509755,18.949465,NaN,1 May 2024,Anne Anthony

In [901]:
male_RS_length = data.loc[(data['Animal type'] == 'Red Squirrel') & (data['Gender'] == 'male'), 'Body Length cm'].mean()

female_RS_length = data.loc[(data['Animal type'] == 'Red Squirrel') & (data['Gender'] == 'female'), 'Body Length cm'].mean()

male_H_length = data.loc[(data['Animal type'] == 'Hedgehog') & (data['Gender'] == 'male'), 'Body Length cm'].mean()

female_H_length = data.loc[(data['Animal type'] == 'Hedgehog') & (data['Gender'] == 'female'), 'Body Length cm'].mean()

In [902]:
data.loc[(data['Animal type'] == 'Red Squirrel') & (data['Gender'] == 'male'), 'Body Length cm'] = male_RS_length

data.loc[(data['Animal type'] == 'Red Squirrel') & (data['Gender'] == 'female'), 'Body Length cm'] = female_RS_length

data.loc[(data['Animal type'] == 'Hedgehog') & (data['Gender'] == 'male'), 'Body Length cm'] = male_H_length

data.loc[(data['Animal type'] == 'Hedgehog') & (data['Gender'] == 'female'), 'Body Length cm'] = female_H_length

In [903]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 999 entries, 2 to 1010
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Animal type       999 non-null    object
 1   Country           999 non-null    object
 2   Weight kg         999 non-null    float64
 3   Body Length cm    999 non-null    float64
 4   Gender            992 non-null    object
 5   Animal code       0 non-null      float64
 6   Latitude          913 non-null    float64
 7   Longitude         913 non-null    float64
 8   Animal name       52 non-null     object
 9   Observation date  999 non-null    object
 10  Data compiled by  999 non-null    object
dtypes: float64(5), object(6)
memory usage: 93.7+ KB

In [904]:
data['Gender'].unique()

array(['male', 'not determined', 'female', nan], dtype=object)

In [905]:
data.loc[data['Gender'] == 'not determined']

,Animal type,Country,Weight kg,Body Length cm,Gender,Animal code,Latitude,Longitude,Animal name,Observation date,Data compiled by
3,European Bison,Poland,909.000,311.0,not determined,NaN,52.830509,23.826849,NaN,01.03.2024,Anne Anthony
43,European Bison,Slovakia,393.000,152.0,not determined,NaN,49.056471,22.422475,NaN,01.03.2024,John Johnson
118,Hedgehog,Hungary,1.100,26.0,not determined,NaN,48.503062,20.551698,NaN,04.03.2024,Anne Anthony
295,Hedgehog,Austria,0.800,24.0,not determined,NaN,47.781689,14.386777,NaN,14.03.2024,Bob Bobson
950,Red Squirrel,Slovakia,0.297,20.0,not determined,NaN,49.054132,22.411066,NaN,03.07.2024,James Johnson

In [906]:
data.loc[data['Gender'].isna()]

,Animal type,Country,Weight kg,Body Length cm,Gender,Animal code,Latitude,Longitude,Animal name,Observation date,Data compiled by
12,Red Squirrel,Poland,0.340,21.0,NaN,NaN,52.240284,21.051948,NaN,01.03.2024,Anne Anthony
54,Red Squirrel,Poland,0.340,21.0,NaN,NaN,52.240284,21.051948,NaN,01.03.2024,Anne Anthony
135,Red Squirrel,Poland,0.291,21.0,NaN,NaN,52.241662,21.056430,NaN,04.03.2024,Anne Anthony
155,Red Squirrel,Poland,0.291,21.0,NaN,NaN,52.241662,21.056430,NaN,04.03.2024,Anne Anthony
260,Red Squirrel,Poland,0.304,22.0,NaN,NaN,52.241093,21.055413,NaN,11.03.2024,Anne Anthony
270,Red Squirrel,Poland,0.304,22.0,NaN,NaN,52.241093,21.055413,NaN,11.03.2024,Anne Anthony
351,Red Squirrel,Slovakia,0.330,18.0,NaN,NaN,48.184757,17.082936,NaN,19.03.2024,John Johnson

For both not determined and null values, we will assign the gender most like characteristics of the animal, in this case if more similar to the mean of weight and length per gender. Since we already have the mean values for both in Red squirrels and hedgehogs, we can begin their

In [907]:
print("Male Hedgehog weight: " + str(male_H_weight))
print("Female Hedgehog weight: " + str(female_H_weight))
print("Male Hedgehog length: " + str(male_H_length))
print("Female Hedgehog length: " + str(female_H_length))

Male Hedgehog weight: 0.8456521739130434
Female Hedgehog weight: 0.7459259259259259
Male Hedgehog length: 20.42753623188406
Female Hedgehog length: 19.392592592592592

Comparing to both unassigned hedgehogs, they closely allign with being males, given their length, since the difference in weight was similar

In [908]:
data.loc[(data['Animal type'] == 'Hedgehog') & (data['Gender'] == 'not determined'), 'Gender'] = 'male'

In [909]:
print("Male Red Squirrel weight: " + str(male_RS_weight))
print("Female Red Squirrel weight: " + str(female_RS_weight))
print("Male Red Squirrel length: " + str(male_RS_length))
print("Female Red Squirrel length: " + str(female_RS_length))

Male Red Squirrel weight: 0.2968996539792388
Female Red Squirrel weight: 0.29127338129496405
Male Red Squirrel length: 20.2560553633218
Female Red Squirrel length: 20.510791366906474

Both of these characteristics are very similar between the males and females, in this case, squirrels of length 22 were decided to be female, and weight >= 0.31 kg to be male

In [910]:
data.loc[(data['Animal type'] == 'Red Squirrel') & (data['Gender'] == 'not determined'), 'Gender'] = 'male'

data.loc[(data['Animal type'] == 'Red Squirrel') & (data['Gender'].isna()) & (data['Weight kg'] >= 0.31 ), 'Gender'] = 'male'
data.loc[(data['Animal type'] == 'Red Squirrel') & (data['Gender'].isna()), 'Gender'] = 'female'

In [911]:
data.loc[data['Gender'] == 'not determined']

,Animal type,Country,Weight kg,Body Length cm,Gender,Animal code,Latitude,Longitude,Animal name,Observation date,Data compiled by
3,European Bison,Poland,909.0,311.0,not determined,NaN,52.830509,23.826849,NaN,01.03.2024,Anne Anthony
43,European Bison,Slovakia,393.0,152.0,not determined,NaN,49.056471,22.422475,NaN,01.03.2024,John Johnson

In [912]:
data.loc[data['Gender'].isna()]

Empty DataFrame
Columns: [Animal type, Country, Weight kg, Body Length cm, Gender, Animal code, Latitude, Longitude, Animal name, Observation date, Data compiled by]
Index: []

Now after completing those we are left with determining the gender of the two European Bison, in this case we will only consider weight, as the difference in weight between the two undetermined is drastic

In [913]:
male_EB_Weight = data.loc[(data['Animal type'] == 'European Bison') & (data['Gender'] == 'male'), 'Weight kg'].mean()

female_EB_Weight = data.loc[(data['Animal type'] == 'European Bison') & (data['Gender'] == 'female'), 'Weight kg'].mean()

In [914]:
print("Male European Bison weight: " + str(male_EB_Weight))
print("Female European Bison weight: : " + str(female_EB_Weight))

Male European Bison weight: 728.0
Female European Bison weight: : 481.1142857142857

There is a clear discrepency in weight like that of the not determined gender entries, these can now be adjusted

In [915]:
data.loc[(data['Animal type'] == 'European Bison') & (data['Gender'] == 'not determined') & (data['Weight kg'] > 600), 'Gender'] = 'male'
data.loc[(data['Animal type'] == 'European Bison') & (data['Gender'] == 'not determined'), 'Gender'] = 'female'

In [916]:
data['Gender'].unique()

array(['male', 'female'], dtype=object)

In [917]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 999 entries, 2 to 1010
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Animal type       999 non-null    object
 1   Country           999 non-null    object
 2   Weight kg         999 non-null    float64
 3   Body Length cm    999 non-null    float64
 4   Gender            999 non-null    object
 5   Animal code       0 non-null      float64
 6   Latitude          913 non-null    float64
 7   Longitude         913 non-null    float64
 8   Animal name       52 non-null     object
 9   Observation date  999 non-null    object
 10  Data compiled by  999 non-null    object
dtypes: float64(5), object(6)
memory usage: 93.7+ KB

Since we have no Animal code data to work with, this column will be excluded from future analysis

In [918]:
data = data.drop(columns=['Animal code'])

In [919]:
data['Animal name'].unique()

array(['Szefu', nan, 'Basia', 'Lolek', 'Lola', 'Bob Bobson', 'Klucha',
       'Zuzia', 'Bibi', 'Sissi', 'Puchatek'], dtype=object)

In [920]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 999 entries, 2 to 1010
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Animal type       999 non-null    object
 1   Country           999 non-null    object
 2   Weight kg         999 non-null    float64
 3   Body Length cm    999 non-null    float64
 4   Gender            999 non-null    object
 5   Latitude          913 non-null    float64
 6   Longitude         913 non-null    float64
 7   Animal name       52 non-null     object
 8   Observation date  999 non-null    object
 9   Data compiled by  999 non-null    object
dtypes: float64(4), object(6)
memory usage: 85.9+ KB

In [921]:
data.loc[data['Latitude'].isna()]

,Animal type,Country,Weight kg,Body Length cm,Gender,Latitude,Longitude,Animal name,Observation date,Data compiled by
13,Red Squirrel,Poland,0.296900,20.256055,male,NaN,NaN,NaN,01.03.2024,Anne Anthony
21,Red Squirrel,Germany,0.296900,20.256055,male,NaN,NaN,NaN,01.03.2024,Bob Bobson
22,Red Squirrel,Germany,0.291273,20.510791,female,NaN,NaN,NaN,01.03.2024,Bob Bobson
23,Red Squirrel,Germany,0.296900,20.256055,male,NaN,NaN,NaN,01.03.2024,Bob Bobson
24,Red Squirrel,Germany,0.291273,20.510791,female,NaN,NaN,NaN,01.03.2024,Bob Bobson
...,...,...,...,...,...,...,...,...,...,...
628,Red Squirrel,Austria,0.291273,20.510791,female,NaN,NaN,NaN,06.04.2024,Bob Bobson
629,Red Squirrel,Austria,0.296900,20.256055,male,NaN,NaN,NaN,06.04.2024,Bob Bobson
630,Red Squirrel,Austria,0.296900,20.256055,male,NaN,NaN,NaN,06.04.2024,Bob Bobson
631,Red Squirrel,Austria,0.296900,20.256055,male,NaN,NaN,NaN,06.04.2024,Bob Bobson
632,Red Squirrel,Austria,0.296900,20.256055,male,NaN,NaN,NaN,06.04.2024,Bob Bobson

In [933]:
PL_RS_Lat = data.loc[(data['Country'] == 'Poland') & (data['Animal type'] == 'Red Squirrel'), 'Latitude'].mean()

In [934]:
data.loc[(data['Animal type'] == 'Red Squirrel') & (data['Country'] == 'Poland') & (data['Latitude'].isna()), 'Latitude'] = PL_RS_Lat

In [935]:
data.loc[data['Latitude'].isna()]

,Animal type,Country,Weight kg,Body Length cm,Gender,Latitude,Longitude,Animal name,Observation date,Data compiled by
21,Red Squirrel,Germany,0.296900,20.256055,male,NaN,NaN,NaN,01.03.2024,Bob Bobson
22,Red Squirrel,Germany,0.291273,20.510791,female,NaN,NaN,NaN,01.03.2024,Bob Bobson
23,Red Squirrel,Germany,0.296900,20.256055,male,NaN,NaN,NaN,01.03.2024,Bob Bobson
24,Red Squirrel,Germany,0.291273,20.510791,female,NaN,NaN,NaN,01.03.2024,Bob Bobson
25,Red Squirrel,Germany,0.296900,20.256055,male,NaN,NaN,NaN,01.03.2024,Bob Bobson
...,...,...,...,...,...,...,...,...,...,...
628,Red Squirrel,Austria,0.291273,20.510791,female,NaN,NaN,NaN,06.04.2024,Bob Bobson
629,Red Squirrel,Austria,0.296900,20.256055,male,NaN,NaN,NaN,06.04.2024,Bob Bobson
630,Red Squirrel,Austria,0.296900,20.256055,male,NaN,NaN,NaN,06.04.2024,Bob Bobson
631,Red Squirrel,Austria,0.296900,20.256055,male,NaN,NaN,NaN,06.04.2024,Bob Bobson
632,Red Squirrel,Austria,0.296900,20.256055,male,NaN,NaN,NaN,06.04.2024,Bob Bobson

In [936]:
G_RS_Lat = data.loc[(data['Country'] == 'Germany') & (data['Animal type'] == 'Red Squirrel'), 'Latitude'].mean()

In [940]:
data.loc[(data['Animal type'] == 'Red Squirrel') & (data['Country'] == 'Germany') & (data['Latitude'].isna()), 'Latitude'] = G_RS_Lat

In [941]:
data.loc[data['Latitude'].isna()]

,Animal type,Country,Weight kg,Body Length cm,Gender,Latitude,Longitude,Animal name,Observation date,Data compiled by
124,Red Squirrel,Hungary,0.296900,20.256055,male,NaN,NaN,NaN,04.03.2024,Anne Anthony
144,Red Squirrel,Hungary,0.296900,20.256055,male,NaN,NaN,NaN,04.03.2024,Anne Anthony
164,Red Squirrel,Austria,0.296900,20.256055,male,NaN,NaN,NaN,05.03.2024,Bob Bobson
626,Red Squirrel,Austria,0.296900,20.256055,male,NaN,NaN,NaN,06.04.2024,Bob Bobson
627,Red Squirrel,Austria,0.291273,20.510791,female,NaN,NaN,NaN,06.04.2024,Bob Bobson
628,Red Squirrel,Austria,0.291273,20.510791,female,NaN,NaN,NaN,06.04.2024,Bob Bobson
629,Red Squirrel,Austria,0.296900,20.256055,male,NaN,NaN,NaN,06.04.2024,Bob Bobson
630,Red Squirrel,Austria,0.296900,20.256055,male,NaN,NaN,NaN,06.04.2024,Bob Bobson
631,Red Squirrel,Austria,0.296900,20.256055,male,NaN,NaN,NaN,06.04.2024,Bob Bobson
632,Red Squirrel,Austria,0.296900,20.256055,male,NaN,NaN,NaN,06.04.2024,Bob Bobson

In [943]:
H_RS_Lat = data.loc[(data['Country'] == 'Hungary') & (data['Animal type'] == 'Red Squirrel'), 'Latitude'].mean()

In [944]:
data.loc[(data['Animal type'] == 'Red Squirrel') & (data['Country'] == 'Hungary') & (data['Latitude'].isna()), 'Latitude'] = H_RS_Lat

In [945]:
A_RS_Lat = data.loc[(data['Country'] == 'Austria') & (data['Animal type'] == 'Red Squirrel'), 'Latitude'].mean()

In [946]:
data.loc[(data['Animal type'] == 'Red Squirrel') & (data['Country'] == 'Austria') & (data['Latitude'].isna()), 'Latitude'] = A_RS_Lat

In [947]:
data.loc[data['Latitude'].isna()]

Empty DataFrame
Columns: [Animal type, Country, Weight kg, Body Length cm, Gender, Latitude, Longitude, Animal name, Observation date, Data compiled by]
Index: []

In [948]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 999 entries, 2 to 1010
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Animal type       999 non-null    object
 1   Country           999 non-null    object
 2   Weight kg         999 non-null    float64
 3   Body Length cm    999 non-null    float64
 4   Gender            999 non-null    object
 5   Latitude          999 non-null    float64
 6   Longitude         913 non-null    float64
 7   Animal name       52 non-null     object
 8   Observation date  999 non-null    object
 9   Data compiled by  999 non-null    object
dtypes: float64(4), object(6)
memory usage: 85.9+ KB

In [949]:
data.loc[data['Longitude'].isna()]

,Animal type,Country,Weight kg,Body Length cm,Gender,Latitude,Longitude,Animal name,Observation date,Data compiled by
13,Red Squirrel,Poland,0.296900,20.256055,male,51.810185,NaN,NaN,01.03.2024,Anne Anthony
21,Red Squirrel,Germany,0.296900,20.256055,male,49.617352,NaN,NaN,01.03.2024,Bob Bobson
22,Red Squirrel,Germany,0.291273,20.510791,female,49.617352,NaN,NaN,01.03.2024,Bob Bobson
23,Red Squirrel,Germany,0.296900,20.256055,male,49.617352,NaN,NaN,01.03.2024,Bob Bobson
24,Red Squirrel,Germany,0.291273,20.510791,female,49.617352,NaN,NaN,01.03.2024,Bob Bobson
...,...,...,...,...,...,...,...,...,...,...
628,Red Squirrel,Austria,0.291273,20.510791,female,47.814592,NaN,NaN,06.04.2024,Bob Bobson
629,Red Squirrel,Austria,0.296900,20.256055,male,47.814592,NaN,NaN,06.04.2024,Bob Bobson
630,Red Squirrel,Austria,0.296900,20.256055,male,47.814592,NaN,NaN,06.04.2024,Bob Bobson
631,Red Squirrel,Austria,0.296900,20.256055,male,47.814592,NaN,NaN,06.04.2024,Bob Bobson
632,Red Squirrel,Austria,0.296900,20.256055,male,47.814592,NaN,NaN,06.04.2024,Bob Bobson

In [950]:
PL_RS_Long = data.loc[(data['Country'] == 'Poland') & (data['Animal type'] == 'Red Squirrel'), 'Longitude'].mean()

In [951]:
data.loc[(data['Animal type'] == 'Red Squirrel') & (data['Country'] == 'Poland') & (data['Longitude'].isna()), 'Longitude'] = PL_RS_Long

In [952]:
G_RS_Long = data.loc[(data['Country'] == 'Germany') & (data['Animal type'] == 'Red Squirrel'), 'Longitude'].mean()

In [953]:
data.loc[(data['Animal type'] == 'Red Squirrel') & (data['Country'] == 'Germany') & (data['Longitude'].isna()), 'Longitude'] = G_RS_Long

In [954]:
data.loc[data['Longitude'].isna()]

,Animal type,Country,Weight kg,Body Length cm,Gender,Latitude,Longitude,Animal name,Observation date,Data compiled by
124,Red Squirrel,Hungary,0.296900,20.256055,male,45.776938,NaN,NaN,04.03.2024,Anne Anthony
144,Red Squirrel,Hungary,0.296900,20.256055,male,45.776938,NaN,NaN,04.03.2024,Anne Anthony
164,Red Squirrel,Austria,0.296900,20.256055,male,47.814592,NaN,NaN,05.03.2024,Bob Bobson
626,Red Squirrel,Austria,0.296900,20.256055,male,47.814592,NaN,NaN,06.04.2024,Bob Bobson
627,Red Squirrel,Austria,0.291273,20.510791,female,47.814592,NaN,NaN,06.04.2024,Bob Bobson
628,Red Squirrel,Austria,0.291273,20.510791,female,47.814592,NaN,NaN,06.04.2024,Bob Bobson
629,Red Squirrel,Austria,0.296900,20.256055,male,47.814592,NaN,NaN,06.04.2024,Bob Bobson
630,Red Squirrel,Austria,0.296900,20.256055,male,47.814592,NaN,NaN,06.04.2024,Bob Bobson
631,Red Squirrel,Austria,0.296900,20.256055,male,47.814592,NaN,NaN,06.04.2024,Bob Bobson
632,Red Squirrel,Austria,0.296900,20.256055,male,47.814592,NaN,NaN,06.04.2024,Bob Bobson

In [955]:
A_RS_Long = data.loc[(data['Country'] == 'Austria') & (data['Animal type'] == 'Red Squirrel'), 'Longitude'].mean()

In [956]:
data.loc[(data['Animal type'] == 'Red Squirrel') & (data['Country'] == 'Austria') & (data['Longitude'].isna()), 'Longitude'] = A_RS_Long

In [960]:
H_RS_Long = data.loc[(data['Country'] == 'Hungary') & (data['Animal type'] == 'Red Squirrel'), 'Longitude'].mean()

In [961]:
data.loc[(data['Animal type'] == 'Red Squirrel') & (data['Country'] == 'Hungary') & (data['Longitude'].isna()), 'Longitude'] = H_RS_Long

In [962]:
data.loc[data['Longitude'].isna()]

Empty DataFrame
Columns: [Animal type, Country, Weight kg, Body Length cm, Gender, Latitude, Longitude, Animal name, Observation date, Data compiled by]
Index: []

In [963]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 999 entries, 2 to 1010
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Animal type       999 non-null    object
 1   Country           999 non-null    object
 2   Weight kg         999 non-null    float64
 3   Body Length cm    999 non-null    float64
 4   Gender            999 non-null    object
 5   Latitude          999 non-null    float64
 6   Longitude         999 non-null    float64
 7   Animal name       52 non-null     object
 8   Observation date  999 non-null    object
 9   Data compiled by  999 non-null    object
dtypes: float64(4), object(6)
memory usage: 85.9+ KB

In [964]:
data['Animal name'].unique()

array(['Szefu', nan, 'Basia', 'Lolek', 'Lola', 'Bob Bobson', 'Klucha',
       'Zuzia', 'Bibi', 'Sissi', 'Puchatek'], dtype=object)

In [966]:
data.loc[data['Animal name'] == 'Bob Bobson', 'Animal name'] = np.nan

In [967]:
data['Animal name'].unique()

array(['Szefu', nan, 'Basia', 'Lolek', 'Lola', 'Klucha', 'Zuzia', 'Bibi',
       'Sissi', 'Puchatek'], dtype=object)

In [968]:
data.loc[data['Animal name'].notna()]

,Animal type,Country,Weight kg,Body Length cm,Gender,Latitude,Longitude,Animal name,Observation date,Data compiled by
2,European Bison,Poland,930.000000,335.000000,male,52.828845,23.820144,Szefu,01.03.2024,Anne Anthony
9,Red Squirrel,Poland,0.291273,20.510791,female,52.241273,21.055745,Basia,01.03.2024,Anne Anthony
11,Red Squirrel,Poland,0.296900,20.256055,male,52.240035,21.056188,Lolek,01.03.2024,Anne Anthony
51,Red Squirrel,Poland,0.291273,20.510791,female,52.241273,21.055745,Basia,01.03.2024,Anne Anthony
53,Red Squirrel,Poland,0.296900,20.256055,male,52.240035,21.056188,Lolek,01.03.2024,Anne Anthony
131,Red Squirrel,Poland,0.291273,20.510791,female,52.240018,21.052390,Lola,04.03.2024,Anne Anthony
136,Red Squirrel,Poland,0.291273,20.510791,female,52.241638,21.055998,Lola,04.03.2024,Anne Anthony
151,Red Squirrel,Poland,0.291273,20.510791,female,52.240018,21.052390,Lola,04.03.2024,Anne Anthony
156,Red Squirrel,Poland,0.291273,20.510791,female,52.241638,21.055998,Lola,04.03.2024,Anne Anthony
282,Red Squirrel,Poland,0.291273,20.510791,female,52.241510,21.052575,Basia,13.03.2024,Anne Anthony
287,Red Squirrel,Poland,0.291273,20.510791,female,52.241510,21.052575,Basia,13.03.2024,Anne Anthony
389,European Bison,Poland,1000.000000,320.000000,male,52.825470,23.813070,Klucha,22.03.2024,Anne Anthony
420,Red Squirrel,Poland,0.291273,20.510791,female,50.041522,19.950563,Zuzia,24.03.2024,Anne Anthony
446,Red Squirrel,Poland,0.291273,20.510791,female,50.041522,19.950563,Zuzia,24.03.2024,Anne Anthony
463,Red Squirrel,Poland,0.296900,20.256055,male,50.041489,19.950768,Lolek,27.03.2024,Anne Anthony
473,Red Squirrel,Poland,0.296900,20.256055,male,50.041489,19.950768,Lolek,27.03.2024,Anne Anthony
482,Red Squirrel,Austria,0.291273,20.510791,female,47.780752,14.383452,Bibi,29.03.2024,Bob Bobson
522,Red Squirrel,Poland,0.291273,20.510791,female,50.041945,19.949320,Lola,02.04.2024,Anne Anthony
556,Red Squirrel,Poland,0.291273,20.510791,female,50.041945,19.949320,Lola,02.04.2024,Anne Anthony
648,Red Squirrel,Austria,0.291273,20.510791,female,47.855379,15.077237,Lola,07.04.2024,Bob Bobson
655,Red Squirrel,Austria,0.291273,20.510791,female,47.854855,15.082168,Sissi,08.04.2024,Bob Bobson
659,Red Squirrel,Austria,0.291273,20.510791,female,47.854756,15.082892,Sissi,08.04.2024,Bob Bobson
785,Red Squirrel,Poland,0.291273,20.510791,female,52.211797,21.033750,Basia,20.04.2024,Anne Anthony
787,Red Squirrel,Poland,0.296900,20.256055,male,52.211872,21.032296,Puchatek,20.04.2024,Anne Anthony
789,Red Squirrel,Poland,0.291273,20.510791,female,52.211797,21.033750,Basia,20.04.2024,Anne Anthony
791,Red Squirrel,Poland,0.296900,20.256055,male,52.211872,21.032296,Puchatek,20.04.2024,Anne Anthony
827,Red Squirrel,Poland,0.291273,20.510791,female,52.212390,21.034548,Basia,29.04.2024,Anne Anthony
830,Red Squirrel,Poland,0.291273,20.510791,female,52.212390,21.034548,Basia,29.04.2024,Anne Anthony
906,Red Squirrel,Poland,0.291273,20.510791,female,52.821524,23.817037,Basia,29.05.2024,Anne Anthony
909,Red Squirrel,Poland,0.291273,20.510791,female,52.821524,23.817037,Basia,29.05.2024,Anne Anthony
987,Red Squirrel,Poland,0.291273,20.510791,female,52.212310,21.033586,Zuzia,4 May 2024,Anne Anthony
988,Red Squirrel,Poland,0.291273,20.510791,female,52.212310,21.033586,Zuzia,4 May 2024,Anne Anthony
1006,Red Squirrel,Poland,0.291273,20.510791,female,52.212001,21.033187,Lola,7 May 2024,Anne Anthony
1009,Red Squirrel,Poland,0.291273,20.510791,female,52.212001,21.033187,Lola,7 May 2024,Anne Anthony

Animal name just seems to be the name given to recorded animals by observers and provides no analytical value due to the small amount recorded. For this reason it will be removed.

In [969]:
data = data.drop(columns=['Animal name'])

In [970]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 999 entries, 2 to 1010
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Animal type       999 non-null    object
 1   Country           999 non-null    object
 2   Weight kg         999 non-null    float64
 3   Body Length cm    999 non-null    float64
 4   Gender            999 non-null    object
 5   Latitude          999 non-null    float64
 6   Longitude         999 non-null    float64
 7   Observation date  999 non-null    object
 8   Data compiled by  999 non-null    object
dtypes: float64(4), object(5)
memory usage: 78.0+ KB